# Generated by Django 3.2.13 on 2022-06-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbo22',
            name='DEPT',
            field=models.CharField(blank=True, choices=[('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('ASSUNTOS REGULATORIOS', 'ASSUNTOS REGULATORIOS'), ('COMERCIAL', 'COMERCIAL'), ('COMERCIAL EXPRESS', 'COMERCIAL EXPRESS'), ('CUSTOMER SERVICE', 'CUSTOMER SERVICE'), ('DIRETOR EXECUTIVO', 'DIRETOR EXECUTIVO'), ('DIRETOR PRESIDENTE E DE OPERACOES', 'DIRETOR PRESIDENTE E DE OPERACOES'), ('EDIFICIOS GUARULHOS', 'EDIFICIOS GUARULHOS'), ('EDIFICIOS OITI', 'EDIFICIOS OITI'), ('GARANTIA DA QUALIDADE', 'GARANTIA DA QUALIDADE'), ('GERENCIA DE PRODUTOS E FORNECEDORES', 'GERENCIA DE PRODUTOS E FORNECEDORES'), ('LOGISTICA', 'LOGISTICA'), ('MARKETING', 'MARKETING'), ('OPERACIONAL', 'OPERACIONAL'), ('PESQUISA E DESENVOLVIMENTO', 'PESQUISA E DESENVOLVIMENTO'), ('PLANEJAMENTO DE MATERIAIS', 'PLANEJAMENTO DE MATERIAIS'), ('PLANEJAMENTO FINANCEIRO - FP&A', 'PLANEJAMENTO FINANCEIRO - FP&A'), ('PRODUCAO', 'PRODUCAO'), ('RECURSOS HUMANOS', 'RECURSOS HUMANOS'), ('TECNOLOGIA DA INFORMACAO', 'TECNOLOGIA DA INFORMACAO'), ('UNIDADE FRAGRANCIAS', 'UNIDADE FRAGRANCIAS'), ('Financeiro', 'Financeiro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22E1A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22E1C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22E2A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22E2C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G1A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G1C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G2A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G2C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G3A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G3C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G4A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G4C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G5A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G5C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G6A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G6C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G7A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC22G7C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23E1A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23E1C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23E2A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23E2C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G1A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G1C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G2A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G2C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G3A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G3C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G4A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G4C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G5A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G5C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G6A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G6C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G7A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC23G7C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24E1A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24E1C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24E2A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24E2C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G1A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G1C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G2A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G2C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G3A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G3C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G4A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G4C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G5A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G5C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G6A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G6C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G7A',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
        migrations.AlterField(
            model_name='adc22',
            name='ADC24G7C',
            field=models.FloatField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1),
        ),
    ]
