from django.utils import timezone
from .models import MBO22,ADC22,RHDT,PDI22#, PDI22G
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from datetime import datetime
from apscheduler.schedulers.background import BackgroundScheduler

User = get_user_model()

def update():

    colaborador2='hyuma.nozaki@cosmotec.com.br'
    resultb = ''
    resultb2 = ''
    resultb3 = ''
    resultb4 = ''
    resultb5 = ''
    resultb6 = 0
    object_list = User.objects.all()
    for l in object_list:
        resultb = l.username
        resultb2 += resultb
        resultb2 += ' '
        resultb3 = str(l.id)
        resultb4 += resultb3
        resultb4 += ' '
    resultb2=resultb2.split()
    resultb4=resultb4.split()
    m=int(len(resultb2))
    for n in range(m):
        if (str(resultb2[n])==colaborador2):
            resultb6=int(resultb4[n])

    AA=''
    for i in object_list:
        try:
            AA+=i.username
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22A1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22AP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22A2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22A3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22A4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22AR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22B1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22BP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22B2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22B3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22B4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22BR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22C1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22CP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22C2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22C3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22C4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22CR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22D1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22DP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22D2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22D3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22D4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22DR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22EP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22E3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22E4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22ER').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22F1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22FP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22F2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22F3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22F4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22FR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]  
            BB=MBO22.objects.values_list('MBO22G1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22GP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22G2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22G3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22G4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO22GR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23A1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23AP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23A2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23A3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23A4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23AR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23B1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23BP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23B2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23B3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23B4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23BR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23C1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23CP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23C2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23C3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23C4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23CR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23D1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23DP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23D2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23D3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23D4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23DR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23EP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23E3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23E4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23ER').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23F1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23FP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23F2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23F3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23F4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23FR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23G1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23GP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23G2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23G3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23G4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO23GR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24A1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24AP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24A2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24A3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24A4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24AR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24B1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24BP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24B2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24B3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24B4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24BR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24C1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24CP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24C2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24C3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24C4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24CR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24D1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24DP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24D2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24D3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24D4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24DR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24EP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24E3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24E4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24ER').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24F1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24FP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24F2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24F3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24F4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24FR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24G1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24GP').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24G2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24G3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24G4').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=MBO22.objects.values_list('MBO24GR').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G1').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G1C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G1A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G1OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G1O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G2').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G2C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G2A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G2OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G2O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G3').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G3C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G3A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G3OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G3O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G4').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G4C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G4A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G4OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G4O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G5').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G5C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G5A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G5OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G5O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G6').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G6C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G6A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G6OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G6O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G7').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G7C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G7A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G7OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22G7O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E1C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E1A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'        
            BB=[]
            BB=ADC22.objects.values_list('ADC22E1OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E1O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E2C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E2A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'        
            BB=[]
            BB=ADC22.objects.values_list('ADC22E2OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E2O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G1').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G1C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G1A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G1OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G1O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G2').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G2C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G2A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G2OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G2O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G3').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G3C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G3A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G3OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G3O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G4').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G4C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G4A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G4OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n' 
            BB=[]
            BB=ADC22.objects.values_list('ADC23G4O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G5').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G5C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G5A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G5OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G5O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G6').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G6C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G6A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G6OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G6O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G7').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G7C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G7A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G7OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23G7O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E1C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E1A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'        
            BB=[]
            BB=ADC22.objects.values_list('ADC23E1OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E1O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E2C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E2A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'        
            BB=[]
            BB=ADC22.objects.values_list('ADC23E2OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E2O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G1').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G1C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G1A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G1OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G1O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G2').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G2C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G2A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G2OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G2O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G3').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G3C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G3A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G3OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G3O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G4').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G4C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G4A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G4OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G4O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G5').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G5C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G5A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G5OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G5O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G6').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G6C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G6A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G6OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G6O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=RHDT.objects.values_list('ADC22G7').get(user=resultb6)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G7C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G7A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G7OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24G7O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E1C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E1A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'        
            BB=[]
            BB=ADC22.objects.values_list('ADC24E1OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E1O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E2C').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E2A').get(user=i.id)
            AA+=str(BB[0])
            AA+='\n'        
            BB=[]
            BB=ADC22.objects.values_list('ADC24E2OC').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E2O').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22G1C').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22G1PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22G1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22G2C').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22G2PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22G2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22G3C').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22G3PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22G3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22E1PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC22E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22E2PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI22E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23G1C').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23G1PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23G1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23G2C').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23G2PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23G2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23G3C').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23G3PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23G3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23E1PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC23E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23E2PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI23E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24G1C').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24G1PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24G1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24G2C').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24G2PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24G2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24G3C').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24G3PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24G3').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24E1PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24E1').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=ADC22.objects.values_list('ADC24E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24E2PD').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
            BB=[]
            BB=PDI22.objects.values_list('PDI24E2').get(user=i.id)
            AA+=BB[0]
            AA+='\n'
        except:
            BB=[]
    subject = "send"
    message = AA
    from_email = 'sistema.rh@cosmotec.com.br'  # 送信
    recipient_list = ['hyuma.nozaki@cosmotec.com.br']  # 宛先リスト
    send_mail(subject, message, from_email, recipient_list)

def start():
    scheduler = BackgroundScheduler()
    scheduler.add_job(update, 'interval', days=1)
    scheduler.start()

